"""Add Employee, CareerPath models and update User model

Revision ID: 2b8b9a5e8b3e
Revises: 456fa548982a
Create Date: 2025-11-22 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8b9a5e8b3e'
down_revision: Union[str, None] = '456fa548982a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_family', sa.String(), nullable=False),
    sa.Column('career_level', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_job_family'), 'career_paths', ['job_family'], unique=False)
    
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    
    # Note: The relationship in User model back-populating to Employee is a pure ORM construct.
    # No database schema change is needed on the 'users' table itself for a one-to-one 'employee' relationship
    # as the foreign key is in the 'employees' table.
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_career_paths_job_family'), table_name='career_paths')
    op.drop_table('career_paths')
    # ### end Alembic commands ###
