"""Add employee_competencies association table

Revision ID: 64bf389418b4
Revises: 2b8b9a5e8b3e
Create Date: 2025-11-22 13:38:07.198690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bf389418b4'
down_revision: Union[str, Sequence[str], None] = '2b8b9a5e8b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_family', sa.String(), nullable=False),
    sa.Column('career_level', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_id'), 'career_paths', ['id'], unique=False)
    op.create_index(op.f('ix_career_paths_job_family'), 'career_paths', ['job_family'], unique=False)
    op.create_table('employee_competencies',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False, comment='Proficiency level from 1 to 5'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'competency_id')
    )
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.drop_constraint(op.f('employees_job_sub_family_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'job_sub_family_id')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('job_sub_family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_job_sub_family_id_fkey'), 'employees', 'job_sub_families', ['job_sub_family_id'], ['id'])
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.drop_column('employees', 'manager_id')
    op.drop_column('employees', 'job_title')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'user_id')
    op.drop_table('employee_competencies')
    op.drop_index(op.f('ix_career_paths_job_family'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_id'), table_name='career_paths')
    op.drop_table('career_paths')
    # ### end Alembic commands ###
