"""add_required_level_to_career_path_competencies

Revision ID: 813b74e37740
Revises: 83545fd3d30d
Create Date: 2025-11-22 23:34:16.895206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813b74e37740'
down_revision: Union[str, Sequence[str], None] = '83545fd3d30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add required_level column with default value for existing rows
    op.add_column('career_path_competencies', sa.Column('required_level', sa.Integer(), nullable=False, server_default='3'))
    # Remove server default after adding column (only needed for migration)
    op.alter_column('career_path_competencies', 'required_level', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove required_level column
    op.drop_column('career_path_competencies', 'required_level')
    # ### end Alembic commands ###
